context:
  version: "0.17.0"

package:
  name: openjph
  version: ${{ version }}

source:
  url: https://github.com/aous72/OpenJPH/archive/${{ version }}.tar.gz
  sha256: 9cd09a5f3a8046b10bded787212afd2410836f9c266964a36f61dc4b63f99b6c

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cmake
    - if: win
      then:
        - ninja
      else:
        - make
  host:
    - libtiff
  run_exports:
    - ${{ pin_subpackage('openjph', upper_bound='x.x') }}

tests:
  - package_contents:
      include:
        - openjph/ojph_version.h
      bin:
        - ojph_compress
        - ojph_expand
      lib:
        # It is still difficult to use these new style tests on windows
        # https://github.com/prefix-dev/rattler-build/issues/1116
        - ${{ "openjph" if unix }}

about:
  homepage: https://github.com/aous72/OpenJPH
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Open source implementation of High-throughput JPEG2000 (HTJ2K).
  repository: https://github.com/aous72/OpenJPH

extra:
  recipe-maintainers:
    - hmaarrfk
